/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.servec.governor.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.servec.governor.models.BadRequest;
import com.servec.governor.models.Pipeline;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-22T04:22:26.530Z")

@Api(value = "{action}", description = "the {action} API")
public interface ActionApi {

	@ApiOperation(value = "Action on a pipeline", nickname = "actionPipelineIdPost", notes = "", tags = { "action", })
	@ApiResponses(value = { @ApiResponse(code = 201, message = "Created"),
			@ApiResponse(code = 400, message = "Bad Request", response = BadRequest.class) })
	@RequestMapping(value = "/{action}/{pipelineId}", produces = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<Void> actionPipelineIdPost(@ApiParam(value = "", required = true) @Valid @RequestBody Pipeline body,
			@ApiParam(value = "", required = true) @PathVariable("pipelineId") Long pipelineId,
			@ApiParam(value = "", required = true, allowableValues = "\"run\", \"stop\"") @PathVariable("action") String action);

}
