/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.servec.governor.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.servec.governor.models.Heartbeat;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-15T06:26:02.812Z")

@Api(value = "heartbeat", description = "the heartbeat API")
public interface HeartbeatApi {

    @ApiOperation(value = "Get Heartbeat of Governor Application", nickname = "heartbeatGet", notes = "", response = Heartbeat.class, tags={ "vitals", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Heartbeat.class) })
    @RequestMapping(value = "/heartbeat",
        method = RequestMethod.GET)
    ResponseEntity<Heartbeat> heartbeatGet();

}
