/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.cgovern.governor.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.cgovern.governor.models.BadRequest;
import com.cgovern.governor.models.Group;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-22T04:22:26.530Z")

@Api(value = "groups", description = "the groups API")
public interface GroupsApi {

	@ApiOperation(value = "Create New Group", nickname = "addGroup", notes = "", response = Group.class, tags = {
			"group", })
	@ApiResponses(value = { @ApiResponse(code = 201, message = "Created", response = Group.class),
			@ApiResponse(code = 400, message = "Bad Request", response = BadRequest.class),
			@ApiResponse(code = 409, message = "Conflict") })
	@RequestMapping(value = "/groups", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.POST)
	ResponseEntity<Group> addGroup(
			@ApiParam(value = "Group object", required = true) @Valid @RequestBody Group body);

	@ApiOperation(value = "Delete existing Group", nickname = "deleteGroupById", notes = "", response = Group.class, tags = {
			"group", })
	@ApiResponses(value = { @ApiResponse(code = 204, message = "No Content", response = Group.class),
			@ApiResponse(code = 404, message = "Not Found") })
	@RequestMapping(value = "/groups/{groupId}", method = RequestMethod.DELETE)
	ResponseEntity<Group> deleteGroupById(
			@ApiParam(value = "", required = true) @PathVariable("groupId") String groupId);

	@ApiOperation(value = "Retrieve Existing Group", nickname = "getGroupById", notes = "", response = Group.class, tags = {
			"group", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = Group.class),
			@ApiResponse(code = 404, message = "Not Found") })
	@RequestMapping(value = "/groups/{groupId}", method = RequestMethod.GET)
	ResponseEntity<Group> getGroupById(
			@ApiParam(value = "", required = true) @PathVariable("groupId") String groupId);

	@ApiOperation(value = "Retrieve All Groups", nickname = "getGroups", notes = "", response = Group.class, responseContainer = "List", tags = {
			"group", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "OK", response = Group.class, responseContainer = "List") })
	@RequestMapping(value = "/groups", method = RequestMethod.GET)
	ResponseEntity<List<Group>> getGroups();

	@ApiOperation(value = "Update existing Group", nickname = "updateGroupById", notes = "", response = Group.class, tags = {
			"role", })
	@ApiResponses(value = { @ApiResponse(code = 204, message = "No Content", response = Group.class),
			@ApiResponse(code = 400, message = "Bad Request", response = BadRequest.class),
			@ApiResponse(code = 404, message = "Not Found") })
	@RequestMapping(value = "/groups/{groupId}", method = RequestMethod.PUT)
	ResponseEntity<Group> updateGroupById(
			@ApiParam(value = "", required = true) @PathVariable("groupId") String groupId,
			@ApiParam(value = "Group Body", required = true) @RequestBody @Valid Group body);

}