/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.cgovern.governor.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.cgovern.governor.models.BadRequest;
import com.cgovern.governor.models.Project;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-22T04:22:26.530Z")

@Api(value = "projects", description = "the projects API")
public interface ProjectsApi {

	@ApiOperation(value = "Create New Project", nickname = "addProject", notes = "", response = Project.class, tags = {
			"project", })
	@ApiResponses(value = { @ApiResponse(code = 201, message = "Created", response = Project.class),
			@ApiResponse(code = 400, message = "Bad Request", response = BadRequest.class),
			@ApiResponse(code = 409, message = "Conflict") })
	@RequestMapping(value = "/projects", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.POST)
	ResponseEntity<Project> addProject(
			@ApiParam(value = "Project object", required = true) @Valid @RequestBody Project body);

	@ApiOperation(value = "Retrieve All Projects", nickname = "getProjects", notes = "", response = Project.class, responseContainer = "List", tags = {
			"project", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "OK", response = Project.class, responseContainer = "List") })
	@RequestMapping(value = "/projects", method = RequestMethod.GET)
	ResponseEntity<List<Project>> getProjects() throws JsonMappingException, JsonProcessingException;

	@ApiOperation(value = "Delete existing Project", nickname = "projectsProjectIdDelete", notes = "", response = Project.class, tags = {
			"project", })
	@ApiResponses(value = { @ApiResponse(code = 204, message = "No Content", response = Project.class),
			@ApiResponse(code = 404, message = "Not Found") })
	@RequestMapping(value = "/projects/{projectId}", method = RequestMethod.DELETE)
	ResponseEntity<Project> projectsProjectIdDelete(
			@ApiParam(value = "", required = true) @PathVariable("projectId") String projectId);

	@ApiOperation(value = "Retrieve Existing Project", nickname = "projectsProjectIdGet", notes = "", response = Project.class, tags = {
			"project", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = Project.class),
			@ApiResponse(code = 404, message = "Not Found") })
	@RequestMapping(value = "/projects/{projectId}", method = RequestMethod.GET)
	ResponseEntity<Project> projectsProjectIdGet(
			@ApiParam(value = "", required = true) @PathVariable("projectId") String projectId);

	@ApiOperation(value = "Update existing Project", nickname = "projectsProjectIdPut", notes = "", response = Project.class, tags = {
			"project", })
	@ApiResponses(value = { @ApiResponse(code = 204, message = "No Content", response = Project.class),
			@ApiResponse(code = 400, message = "Bad Request", response = BadRequest.class),
			@ApiResponse(code = 404, message = "Not Found") })
	@RequestMapping(value = "/projects/{projectId}", method = RequestMethod.PUT)
	ResponseEntity<Project> projectsProjectIdPut(
			@ApiParam(value = "", required = true) @PathVariable("projectId") String projectId,
			@ApiParam(value = "Project object", required = true) @Valid @RequestBody Project body);

}
