name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload to Packages
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/ravivamsi -Dtoken=1729bfd4ff8b8c1bd3d27ed49f5b90ed5ca8d50d
